name: activities_repository
description: A new Flutter package project.
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  bored_api:
    path: ../bored_api
  equatable: ^2.0.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
