name: bored_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  equatable: ^2.0.5
  activities_repository:
    path: packages/activities_repository

dev_dependencies:
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
